//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strata.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Strata.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMAND:&gt;.
        /// </summary>
        internal static string ConsoleCommandPrompt {
            get {
                return ResourceManager.GetString("ConsoleCommandPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console command entered: {0}.
        /// </summary>
        internal static string ConsoleEnteredCommand {
            get {
                return ResourceManager.GetString("ConsoleEnteredCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceManager is null.  Cannot refresh..
        /// </summary>
        internal static string ConsoleErrorServiceManagerNull {
            get {
                return ResourceManager.GetString("ConsoleErrorServiceManagerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit requested from console..
        /// </summary>
        internal static string ConsoleExitting {
            get {
                return ResourceManager.GetString("ConsoleExitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command: {0}Known commands:      exit - Exits the application.     refresh - Refreshes the server&apos;s services..
        /// </summary>
        internal static string ConsoleHelp {
            get {
                return ResourceManager.GetString("ConsoleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing services done..
        /// </summary>
        internal static string ConsoleRefreshedServices {
            get {
                return ResourceManager.GetString("ConsoleRefreshedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing services....
        /// </summary>
        internal static string ConsoleRefreshingServices {
            get {
                return ResourceManager.GetString("ConsoleRefreshingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDS - X-Wing Services Platform started in &gt;&gt; DEBUG &lt;&lt; mode..
        /// </summary>
        internal static string ConsoleWarnDebugMode {
            get {
                return ResourceManager.GetString("ConsoleWarnDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not cast service as IService: {0}.
        /// </summary>
        internal static string ErrorCannotCastService {
            get {
                return ResourceManager.GetString("ErrorCannotCastService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateContainer may only be called once per session..
        /// </summary>
        internal static string ErrorContainerFactoryCreateOnlyOnce {
            get {
                return ResourceManager.GetString("ErrorContainerFactoryCreateOnlyOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity: Interface [IExceptionManager] mapped to type [ExceptionManagerFacade]..
        /// </summary>
        internal static string InterfaceMappedExceptionManager {
            get {
                return ResourceManager.GetString("InterfaceMappedExceptionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity: Interface [ILogger] mapped to type [LoggerFacade]..
        /// </summary>
        internal static string InterfaceMappedLogger {
            get {
                return ResourceManager.GetString("InterfaceMappedLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity: Interface [ISecurityProvider] mapped to type [ActiveDirectorySecurityProvider]..
        /// </summary>
        internal static string InterfaceMappedSecurityProvider {
            get {
                return ResourceManager.GetString("InterfaceMappedSecurityProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity: Interface [IServiceMessageFactory] mapped to type [ServiceMessageFactory]..
        /// </summary>
        internal static string InterfaceMappedServiceMessageFactory {
            get {
                return ResourceManager.GetString("InterfaceMappedServiceMessageFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.  De-briefing at oh-eight-thirty..
        /// </summary>
        internal static string ServiceManagerStoppedServices {
            get {
                return ResourceManager.GetString("ServiceManagerStoppedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping services....
        /// </summary>
        internal static string ServiceManagerStoppingServices {
            get {
                return ResourceManager.GetString("ServiceManagerStoppingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Manager.
        /// </summary>
        internal static string ServiceManagerThread {
            get {
                return ResourceManager.GetString("ServiceManagerThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed WCF endpoint for {0}..
        /// </summary>
        internal static string ServiceManagerWCFClosed {
            get {
                return ResourceManager.GetString("ServiceManagerWCFClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing WCF endpoint for {0}..
        /// </summary>
        internal static string ServiceManagerWCFClosing {
            get {
                return ResourceManager.GetString("ServiceManagerWCFClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Manager: WCF Service hosted on URL [{0}]..
        /// </summary>
        internal static string ServiceManagerWCFHosted {
            get {
                return ResourceManager.GetString("ServiceManagerWCFHosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDS - X-Wing Services Platform commencing operations..
        /// </summary>
        internal static string SystemStarted {
            get {
                return ResourceManager.GetString("SystemStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDS - X-Wing Services Platform ceasing operations at request..
        /// </summary>
        internal static string SystemStopped {
            get {
                return ResourceManager.GetString("SystemStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity: Extension added..
        /// </summary>
        internal static string UnityAddedExtension {
            get {
                return ResourceManager.GetString("UnityAddedExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity: Policy added: {0}.
        /// </summary>
        internal static string UnityAddedPolicy {
            get {
                return ResourceManager.GetString("UnityAddedPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity: Adding interception extension to container....
        /// </summary>
        internal static string UnityAddingInterceptionExtension {
            get {
                return ResourceManager.GetString("UnityAddingInterceptionExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity: Container configured..
        /// </summary>
        internal static string UnityConfiguredContainer {
            get {
                return ResourceManager.GetString("UnityConfiguredContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity: Enterprise Library application blocks configured..
        /// </summary>
        internal static string UnityConfiguredEntLib {
            get {
                return ResourceManager.GetString("UnityConfiguredEntLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity: Interception configured..
        /// </summary>
        internal static string UnityConfiguredInterception {
            get {
                return ResourceManager.GetString("UnityConfiguredInterception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity: Configuring container....
        /// </summary>
        internal static string UnityConfiguringContainer {
            get {
                return ResourceManager.GetString("UnityConfiguringContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity: Applying Enterprise Library configuration to the container....
        /// </summary>
        internal static string UnityConfiguringEntLib {
            get {
                return ResourceManager.GetString("UnityConfiguringEntLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity: Configuring interception....
        /// </summary>
        internal static string UnityConfiguringInterception {
            get {
                return ResourceManager.GetString("UnityConfiguringInterception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity: Container created..
        /// </summary>
        internal static string UnityCreatedContainer {
            get {
                return ResourceManager.GetString("UnityCreatedContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity: Creating container....
        /// </summary>
        internal static string UnityCreatingContainer {
            get {
                return ResourceManager.GetString("UnityCreatingContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently running.  Stopping....
        /// </summary>
        internal static string WarnStoppingRunningService {
            get {
                return ResourceManager.GetString("WarnStoppingRunningService", resourceCulture);
            }
        }
    }
}
